config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  get 'conversations/index'
  devise_for :users
  root to: 'conversations#index'
  resources :conversations, only: [:create] do
    resources :messages, only: [:index, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id, recipient_id) do
    where('(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)', sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
 belongs_to :conversation
 belongs_to :user
 validates_presence_of :content, :conversation_id, :user_id

 def message_time
  created_at.strftime('%m/%d/%y at %l:%M %p')
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  NAME_REGEX = /\w+/
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       format: { with: /\A#{NAME_REGEX}\z/i },
                       length: { maximum: 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
   @users = User.all
   @conversations = Conversation.all
   end

  def create
   if Conversation.between(params[:sender_id],params[:recipient_id])
     .present?
      @conversation = Conversation.between(params[:sender_id],
       params[:recipient_id]).first
   else
    @conversation = Conversation.create!(conversation_params)
   end
   redirect_to conversation_messages_path(@conversation)
  end

  private

   def conversation_params
    params.permit(:sender_id, :recipient_id)
   end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :get_messages

  def index
    @message  = @conversation.messages.new
  end

  def create
     @message = @conversation.messages.new(message_params)
    if @message.save
      ActionCable.server.broadcast "conversation_#{@conversation.id}",
                                   message:  render_message(@message),
                                   conversation: @conversation.id
    else
      render 'index'
    end
  end

  private

  def get_messages
    @conversation = Conversation.find(params[:conversation_id])
    @messages = @conversation.messages
  end

  def message_params
    params.require(:message).permit(:content, :user_id)
  end
    def render_message(message)
      render(partial: 'message', locals: { message: message })
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/conversations/index.html.erb
<div class="container">
    <div class="row">
        <div class='col-6'>
            <h3>Mailbox</h3>
            <div class='ui list'>
                <div class='item'>
                    <% @conversations.each do |conversation| %>
                    <% if conversation.sender_id == current_user.id ||      conversation.recipient_id == current_user.id %>
                    <% if conversation.sender_id == current_user.id %>
                    <% recipient = User.find(conversation.recipient_id) %>
                    <% else %>
                    <% recipient = User.find(conversation.sender_id) %>
                    <% end %>
                    <%= link_to recipient.username,   conversation_messages_path(conversation)%>
                    <% end %>
                    <% end %>
                </div>
            </div>
        </div>
        <div class='col-6'>
            <h3>All Users</h3>
            <div class='ui list'>
                <% @users.each do |user| %>
                <% if user.id != current_user.id %>
                <div class='item'>
                    <%= user.username %>
                    <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
                </div>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CableTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
    <div class="message-user">
        <%= message.user.username %>:
    </div>
    <div class="message-content">
        <%= message.content %>
    </div>
</div>

app/views/messages/_message_form.html.erb
<div class="message-input">
  <%= simple_form_for [@conversation, @message], remote: true do |f| %>
   <%= f.input :user_id, input_html: { value: current_user.id }, as: :hidden %>
    <%= f.input :content %>
    <%= f.submit "Send", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/messages/_messages.html.erb
<div id="messages" class="messages">
    <div id="messages-table" class="messages-table" data-id='<%= @conversation.id %>'>
        <% if @messages.any? %>
        <% @messages.each do |message| %>
          <% if message.id %>
            <%= render 'message', message: message %>
          <% end %>
        <% end %>
        <% end %>
    </div>
</div>

app/views/messages/index.html.erb
<div class="message-wr">
  <%= render 'messages' %>
  <%= render 'message_form' %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log Out", destroy_user_session_path, method: 'delete', class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>